= DISID Slides
:templateurl: https://github.com/paulrouget/dzslides/blob/master/template.html
:backendurl: https://github.com/mojavelinux/asciidoc-dzslides-backend/blob/master/dzslides.conf

A repository of DISID's slides animated by
http://paulrouget.com/dzslides/[DZSlides].

The presentations are written in AsciiDoc, generated by the AsciiDoc toolchain 
and presented in HTML5 using Dan Allen's
https://github.com/mojavelinux/dzslides[fork of dzslides].

Slides are based on Dan Allen's https://github.com/mojavelinux/decks/[slides]. 

Thanks to:

* https://github.com/mojavelinux[Dan Allen] for sharing his slides and
  resources.
* https://github.com/paulrouget[Paul Rouge] for DZSlides, a modern 
  presentation framework based on HTML5 and CSS3.

== Setting up the build environment

Follow these instructions (for *nix) to setup AsciiDoc to generate DZSlides 
presentations from the AsciiDoc source file:

* Install http://asciidoc.org[AsciiDoc] (8.6.6 or newer). Ensure that the 
  command `asciidoc` is available on your `PATH`.

* Fetch and setup the _dzslides_ AsciiDoc backend by installing it into 
  asciidoc backends through git (you will need AsciiDoc version 8.6.6 or newer):
+
----
mkdir -p $HOME/.asciidoc/backends
cd $HOME/.asciidoc/backends
git clone git://github.com/mojavelinux/asciidoc-dzslides-backend.git dzslides
cd dzslides
git clone git://github.com/mojavelinux/dzslides.git
----

== Build a presentation

Follow these build instructions to generate a dzslide presentation from the 
AsciiDoc source files.

First, change into directory that contains the presentation AsciiDoc files.

Next, generate a standalone HTML file that embeds all assets (stylesheets, JavaScript sources and images).

----
asciidoc -a data-uri -a linkcss! slides.adoc
----

You can now view the presentation slides.html in your browser.

[NOTE]
====
This repository contains the _gen-slides.sh_ tool that could help you to
generate your presentation.
====

If you want to link to the assets, you can just run the asciidoc command 
without any arguments:

----
asciidoc slides.asciidoc
----

However, you also need to create a symlink to the dzslides project so that the linked assets can be located.

----
ln -s $HOME/.asciidoc/backends/dzslides/dzslides dzslides
----

== Additional resources

DZSlides {templateurl}[template.html] is the only file you need to know how
DZSlides works. Edit the file, read and learn. To see the slides in action,
just load that file in your browser.

Read {backendurl}[dzslides.conf] to know how AsciiDoc dzslides backend works
to renders the AsciiDoc source as a dzslides presentation.

Good luck!

