//
// Build the presentation
//
// dzslides with embedded assets:
// asciidoc -a data-uri -a linkcss! slides.adoc
//
// HTML5:
// asciidoc -b html5 -o outline.html slides.adoc
//
**gvNIX** el estándar de desarrollo Java de la Generalitat
==========================================================
DISID CORPORATION, @disid_corp <eruiz@disid.com>
v1.0, Apr 08, 2014
:title: gvNIX, el estándar de desarrollo Java de la Generalitat 
:description: Slides for DISID presentation about developing with gvNIX delivered at Semana Informatica 2014.
:copyright: CC BY-NC-SA 3.0
:website: http://www.disid.com
:slidesurl: https://github.com/DISID/disid-decks
:imagesdir: images
:backend: dzslides
:linkcss: true
//:dzslides-style: stormy
:dzslides-style: tomorrow
:dzslides-transition: fade
:dzslides-aspect: 16-9
:dzslides-fonts: family=Yanone+Kaffeesatz:400,700,200,300&family=Cedarville+Cursive
:dzslides-highlight: monokai
// disable syntax highlighting unless turned on explicitly
:syntax: no-highlight

== \\

[quote, Joan Clos (2003)]
____
El endeudamiento de las administraciones locales se verá reducida 
en el futuro por ley.
____

[template="notesblock"]
====
Esta advertencia que hizo Joan Clos en las Jornadas "Internet & City" del 
2003, es ya una realidad y la administración está reduciendo el actual nivel 
de inversiones para reducir el gasto corriente.

Reducción que repercute directamente en los servicios que nos presta la
administración a los ciudadanos.
====

== \\

[{statement}]
*DGTI* la propuesta de la Generalitat

[template="notesblock"]
====
Ante esta situación, en 2011 la Generalitat creó la 
Dirección General de Tecnologías de la Información (DGTI) 
dependiente de la Conselleria de Hacienda y Administración Pública, que asumió 
la gestión de recursos y la provisión de servicios TIC de la Generalitat.

Se puso en marcha la centralización de la gestión de las TIC de la 
Generalitat en un único departamento, después de 30 años de competencias 
distribuidas entre las consellerias.

El objetivo fundamental de este cambio es eliminar gastos redundantes, 
aprovechar las sinergias entre los distintos departamentos, y obtener los 
ahorros propios de las economía de escala.

Esta reducción del gasto es peligrosa ya que de no hacerse bien puede derivar
en eliminar inversiones y dedicar los recursos "sólo" a mantener los mismos
servicios

Se hace por tanto necesaria una transformación sostenible de las 
infraestructuras y los sistemas de información, es decir, las inversiones se 
dirigen a transformar y mejorar los servicios, lo que debería provocar una 
reducción de los gastos de mantenimiento a medio y largo plazo.
====

== \\

[{statement}]
Dar *más servicios*
con *menos costes* {nbsp} {nbsp}

[template="notesblock"]
====
Actualmente la administración pública ofrece servicios a través de Internet y 
nos hemos acostumbrado a interactuar con la administración de forma digital,
además en algunos casos nos gustaría tener un papel activo de co-creador, de 
generador de contenidos, de generador de conocimiento a través de cualquier 
medio, PC, móvil o tableta.

Poco a poco se ofrecen nuevas formas de conectar con los usuarios, 
orientanado las aplicaciones hacia entornos móviles como forma de entender y 
atender la relación con los ciudadanos, así como demostrar mayor transparencia 
compartiendo información pública.

El gran reto de las administraciones públicas y de los procesos de
transformación consiste en mantener y ampliar los servicios al ciudadano a 
través de las TIC ... todo ello con menores costes.

*PREGUNTA AL PUBLICO*

En lo que respecta a sistemas de información, ¿alguien me dice qué pueden 
hacer las aapp para solucionar ésta papeleta que tienen entre manos?

====

== \\

[{statement}]
Mayor *productividad*

[template="notesblock"]
====
Es importante que la administración pública sea capaz de conseguir un
*aumento de la productividad* TIC como uno de los factores esenciales para 
hacer frente a estos retos.

Mientras que en la última década se han conseguido aumentos espectaculares en
la productividad en sectores industriales, el aumento conseguido en el 
promedio de las administraciones públicas es muy bajo.

Por tanto, hay un gran "filón de aumento de la productividad" posible en las 
administraciones, un elevado margen de transformación hacia una mayor 
eficiencia.

Las condiciones económicas actuales no da más alternativa que explotar este 
filón, y dar, en efecto, "más por menos" a los ciudadanos.
====

== \\

[{statement}]
Nuevas formas de *aumentar* la *eficiencia*

[template="notesblock"]
====
Ese aumento de la productividad se sustenta entre otros en una 
reorganización e integración de procedimientos y procesos, evitando 
duplicidades y aprovechando recursos entre las diferentes unidades 
de una administración.

Hay que poner en cuestión la forma de los procedimientos, los flujos de trabajo
de los procesos. Por tanto, es importante que se permita innovar a las 
diferentes unidades de la administración, estimular la
reinvención en aras de mayor eficiencia.

Esta estimulación de la innovación en las administraciones es otro de los 
retos críticos. Se hace necesario buscar mecanismos de estímulo,
reconocimiento e incluso remuneración de los innovadores, con el fin de buscar
formas de aumentar la eficiencia, y conseguir así ese necesario aumento de la
productividad.
====

== \\

[{statement}]
Incremento de la *participación ciudadana*

[template="notesblock"]
====
El aumento de la eficiencia debe venir acompañada por otro motor importante de 
transformación: la participación de los ciudadanos. 
Internet permite un nivel de participación impensable hace 
pocos años. Los ciudadanos pueden opinar, aportar sugerencias, vehicular sus 
quejas, hacer preguntas, con un dinamismo que puede resultar de gran utilidad 
tanto al administrado como a las admnistraciones.

Por poner un ejemplo, el ciudadano puede aportar información muy afinada, y 
totalmente actualizada, sobre el estado de un determinado punto de la 
geografía de una carretera ("en este calle hay un bache"), de una ciudad 
("los contenedores de reciclado de plástico están llenos", etc).

El salto desde las webs que informan al ciudadano, hacia estos 
"sistemas públicos de información" (el ciudadano como informador 
a la administración), son sólo un ejemplo del aumento de la participación útil 
del ciudadano en la gestión de su comunidad.
====

== \\

[{statement}]
*DGTI* el *motor* del cambio

[template="notesblock"]
====
Para dar solución a esta problemática, en 2011 la Generalitat creó la 
Dirección General de Tecnologías de la Información (DGTI) 
dependiente de la Conselleria de Hacienda y Administración Pública, que asumió 
la gestión de recursos y la provisión de servicios TIC de la Generalitat.

Es decir, se puso en marcha la centralización de la gestión de las TIC de la 
Generalitat en un único departamento, después de 30 años de competencias 
distribuidas entre las consellerias.

El objetivo fundamental de este cambio es eliminar gastos redundantes, 
aprovechar las sinergias entre los distintos departamentos, y obtener los 
ahorros propios de las economías de escala.
====

== \\

GVA Cloud (en gris claro) : Añadir URL a hoja de ruta
Telefonía IP
Puesto de trabajo TIC
Seguridad TIC
Nueva Oficina Judicial
ITA
Agenda Digital

Gobernanza
*Estandarización*
Gestión económica

[template="notesblock"]
====
El modelo centralizado de gestión de las TIC permite abordar la estandarización 
de los activos TIC de la Generalitat.

El proceso de estandarización se está llevando a cabo, entre otros, para los 
siguientes tipos de activos:

* Puesto de trabajo del empleado público
* Infraestructuras de red en los edificios
* Software

En esta línea se incluyen las actuaciones para la estandarización de las 
tecnologías relativas a las aplicaciones.

En concreto se están definiendo estándares sobre la arquitectura y las 
tecnologías del software de todo tipo (ej. tecnología de portales, de gestión 
documental o de gestión de expedientes), y sobre las metodologías y 
herramientas para el desarrollo de aplicaciones.

Es decir, más por menos, en el desarrollo y mantenimiento de aplicaciones!

====

== \\

[{statement}]
Software de *código abierto*

[template="notesblock"]
====
Sin embargo, estos retos pueden brindar oportunidades únicas para fomentar la innovación en la administración pública y hacerla más eficiente y transparente. Ante esta coyuntura, emerge como alternativa el uso del software libre. No obstante, justificar el uso estratégico del software libre solo con base en los costos de adquisición sería adoptar una visión limitada sobre el aporte que este tipo de software puede ofrecer ante los retos que la administración pública enfrenta en la actualidad.

En este campo es necesario disponer de plataformas que permitan a las 
diferentes administraciones intercambiar sus experiencias, sus mejores 
prácticas, con el fin de aprender rápidamente de los éxitos y fracasos de los 
demás, y avanzar así más eficazmente en ese camino de innovación permanente 
en el servicio de las administraciones públicas al ciudadano.

Otro de los factores que tienen un protagonismo relevante es el uso de 
programas de código abierto y estándares, que permiten a las administraciones 
centrar su inversión en la creación de contenidos y servicios de verdadera 
utilidad al ciudadano en lugar de dedicar los recursos simplemente a pagar 
licencias a los grandes fabricantes de software.
====

////

== Resources

////
